# conda_recipe/meta.yaml

package:
  name: playwright_utils
  version: "0.1.0"

source:
  path: ..

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - playwright
    - python-dotenv
    - configparser
    - agentql

test:
  imports:
    - playwright_utils

about:
  home: https://github.com/OzMaatuk/JobApplicationAutomation
  license: MIT
  license_file: LICENSE
  summary: ""
  description: ""
extra:
  recipe-maintainers:
    - Oz Levi